global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Payment_Group5.Controllers;
global using Payment_Group5.Models;
global using PaymentModuleDemo;
global using System.Net.Http;
global using System.Transactions;
global using Transaction = PaymentModuleDemo.Transaction;
global using PaymentModuleDemo.Models;